### ISSUE TITLE
facesDidUpdate function keep calling even when the FacePicker component unmouted

### ISSUE THREAD

**Issue by knight3001** [anisjonischkeit/FacePicker#1]
currently, I checked in the parent component, wrapped the facesDidUpdate function to check whether ImagusFacePicker exist, otherwise not call setState

**Comment by anisjonischkeit** [comment]
Whoops, I didn't see this. Did you end up fixing this one?

**Comment by knight3001** [comment]
Hi, Anis, I just saw this...
Yer, I fixed it in a way.
I looked at your code, that's clearer than my way, thanks.

**Comment by anisjonischkeit** [comment]
no worries, It's also removed the other listeners.
